### ISSUE TITLE
Correct format for DataQuery coords?

### ISSUE THREAD

**Issue by crbunney** [opengeospatial/ogcapi-environmental-data-retrieval#360]
Hi,
I'm implementing an EDR server, currently on the DataQuery portions of the Collection metadata response.

I've been looking at the OpenAPI definitions for DataQuery.yaml (on both the `master` branch and `1.0.0-draft.1` tag) and the examples given for `coords` don't seem to match the schema.

For example, consider this extract from [positionDataQuery.yaml](https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/blob/0e087e44f5314eed590271cbacbfaccd7d1e0a40/standard/openapi/schemas/positionDataQuery.yaml) on `master`: 
```yaml
  coords:
    description:  Well Known Text Point which describes the required position
    type: object
    properties:
      description:
        type: string
      type:
        type: string
    example: POINT(0 51.48)
```

The example is a string, rather than an object?

The schema suggests to me that the response is intended to look like this:
```yaml
coords:
    description: ???
    type: ???
```
(I've put the `???` because I'm not sure what is expected to go into these fields)

Whereas the example suggests the response should look like this:
```yaml
coords: POINT(0 51.48)
```

Is anyone able to clarify this for me please?

**Comment by m-burgoyne** [comment]
Hi @crbunney the coords attribute was originally intended to provide an information on how the coords query parameters are constructed in the collections metadata response.  It is duplicating the information that is more clearly defined in the 
OpenAPI schemas for the query patterns and is optional.  

coords:
    description: Well Known Text Point which describes the required position
    type: POINT(0 51.48)

**Comment by crbunney** [comment]
Thanks @m-burgoyne 

I'm no OpenApi expert, but does that then mean that this would be a more accurate representation?

```yaml
coords:
    type: object
    properties:
      description:
        type: string
        example: Well Known Text Point which describes the required position
      type:
        type: string
        example: POINT(0 51.48)
```
