### ISSUE TITLE
parameter-names property in collection.yaml

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/ogcapi-environmental-data-retrieval#369]
[collection.yaml](http://schemas.opengis.net/ogcapi/edr/1.0/openapi/schemas/collection.yaml) declares:

```yaml
type: object
required:
  - links
  - id
  - extent
  - parameter-names
```

Then lower down in the file the element is defined as:

```yaml
  parameter_names:
    description: list of the data parameters available in the collection
    type: object
    additionalProperties:
      items:
        $ref: parameter.yaml
```

So the issue is inconsistency between `parameter-names` and `parameter_names`.
