### ISSUE TITLE
Fix extent.yaml schema error

### ISSUE THREAD

**Issue by m-burgoyne** [opengeospatial/ogcapi-environmental-data-retrieval#401]
The [extent.yaml](https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/blob/master/standard/openapi/schemas/collections/extent.yaml) has an indentation error in the bbox definition

```yaml
    oneOf:
      - items:
          minItems: 4
          maxItems: 4
          type: number
        type: array  
      - items:
          minItems: 6
          maxItems: 6
          type: number
        type: array  
```

should be
```yaml
          oneOf:
            - items:
                type: number
              minItems: 4
              maxItems: 4
              type: array  
            - items:
                type: number
              minItems: 6
              maxItems: 6
              type: array  
```
