### ISSUE TITLE
Support multiple implementations of pubsub for one data collection

### ISSUE THREAD

**Issue by mvisa** [opengeospatial/ogcapi-environmental-data-retrieval#457]
Assume we have a collection of some data. There is a need to publish updates via pubsub but simultaneously via two different pubsub standards/implementations. So the same updates of new data could be pushed via AMQP and MQTT (for example). How can this be accomplished and does the current standard allow this? Should be verified that nothing limits this in AsyncAPI or EDR standard. Or maybe it's already possible, not sure.

I see a use case with aviation data as the SWIM standard mandates AMQP while at the same time we may have to publish updates to the same data via MQTT say for example to WMO WIS2.

**Comment by ShaneMill1** [comment]
Hey @mvisa, I think this can be done within AsyncAPI, where you can describe the two different protocols within the server section, such as:

```
servers:
  mqtt:
    url: ec2-52-204-134-57.compute-1.amazonaws.com:{port}
    protocol: mqtt
    protocolVersion: 3.1.1
    description: MQTT end point
    variables:
      port: 
        enum: 
          - "1883"
        default: "1883"
    security:
      - X-API-KEY: ['']
  amqp:
    url: ec2-52-204-134-57.compute-1.amazonaws.com:{port}
    protocol: amqp
    protocolVersion: 1.0.0
    description: AMQP end point
    variables:
      port: 
        enum: 
          - "5672"
        default: "5672"
    security:
      - X-API-KEY: ['']
```
